site_name: WgpArch Awesome WM Config
site_url: https://wgparch.codeberg.page/awesome/
theme:
  name: material
  palette:
    primary: cyan
    accent: light blue
  features:
    - navigation.tabs
    - navigation.expand
nav:
  - Home: index.md
  - Installation: installation.md
  - Keybinds: keybinds.md
  - Look & Feel: theming.md
  - Rofi Menus: rofi.md
  - Gallery: gallery.md
  - Credits & Attribution: credits.md
